name: demandium
description: A new Flutter application.
publish_to: 'none' #
version: 1.0.8+11

environment:
  sdk: ^3.4.0  # Updated SDK version

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  get: ^4.6.6
  intl: ^0.20.2
  shared_preferences: ^2.3.5
  connectivity_plus: ^6.1.1
  firebase_core: ^3.10.0
  firebase_messaging: ^15.2.0
  path_provider: ^2.1.5
  url_strategy: ^0.3.0
  firebase_analytics: ^11.4.2
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  google_maps_flutter: ^2.10.0
  geolocator: ^13.0.2
  url_launcher: ^6.3.1
  country_code_picker: ^3.1.0
  phone_numbers_parser: ^9.0.3
  webview_flutter: ^4.10.0
  pin_code_fields: ^8.0.1
  flutter_widget_from_html_core: ^0.15.2
  flutter_typeahead: ^5.2.0
  pointer_interceptor: ^0.10.1+2
  shimmer_animation: ^2.2.2
  carousel_slider: ^5.0.0
  google_sign_in: ^6.2.2
  flutter_facebook_auth: ^6.0.4
  smooth_page_indicator: ^1.2.0+3
  expandable: ^5.0.1
  file_picker: ^8.1.7
  flutter_html: ^3.0.0-alpha.6
  flutter_local_notifications: ^18.0.1
  universal_html: ^2.2.4
  flutter_inappwebview: ^6.1.5
  timeago: ^3.7.0
  pdf: ^3.11.1
  local_auth: ^2.0.0
  diffutil_dart: ^4.0.1
  flutter_downloader: ^1.11.8
  permission_handler: ^11.3.1
  fluttertoast: ^8.2.10
  printing: ^5.13.4
  audioplayers: ^6.1.0
  dotted_border: ^2.1.0
  expandable_bottom_sheet: ^1.1.1+1
  share_plus: ^10.1.3
  rect_getter: ^1.1.0
  scroll_to_index: any
#  http_parser: ^4.1.2
#  http: ^1.2.2
  path: ^1.9.0
  syncfusion_flutter_datepicker: ^28.1.38
  sign_in_with_apple: ^6.1.2
  uuid: ^4.5.1
  just_the_tooltip: ^0.0.12
  label_marker: ^1.0.1
  custom_info_window: ^1.0.1
  custom_marker: ^1.0.0
  photo_view: ^0.15.0
  flutter_slidable: ^3.1.1
  app_links: ^6.3.2
  syncfusion_flutter_sliders: ^28.1.38
  syncfusion_flutter_core: ^28.1.38
  flutter_xlider: ^3.5.0
  video_player: ^2.9.2
  chewie: ^1.9.0
  firebase_auth: ^5.4.0
  readmore: ^3.0.0
  lottie: ^3.3.0
  cached_network_image_platform_interface:
  drift: ^2.19.0
  drift_flutter: ^0.1.0
  get_storage: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  drift_dev: ^2.19.0
  build_runner: ^2.4.13

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/language/
    - assets/json/
    - assets/map/
    - assets/
    - assets/images/user_logo.png

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/font/Roboto-Light.ttf
          weight: 300
        - asset: assets/font/Roboto-Regular.ttf
          weight: 400
        - asset: assets/font/Roboto-Medium.ttf
          weight: 500
        - asset: assets/font/Roboto-Bold.ttf
          weight: 700
